#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Stewart_Control.Resource", IsApplication=true)]

namespace Stewart_Control
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_action_overflow = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int xs = 2130837506;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070001
			public const int button1a = 2131165185;
			
			// aapt resource value: 0x7f070013
			public const int button1i = 2131165203;
			
			// aapt resource value: 0x7f070017
			public const int linearLayout1 = 2131165207;
			
			// aapt resource value: 0x7f070023
			public const int linearLayout10 = 2131165219;
			
			// aapt resource value: 0x7f070027
			public const int linearLayout11 = 2131165223;
			
			// aapt resource value: 0x7f07002b
			public const int linearLayout12 = 2131165227;
			
			// aapt resource value: 0x7f07002f
			public const int linearLayout13 = 2131165231;
			
			// aapt resource value: 0x7f070037
			public const int linearLayout14 = 2131165239;
			
			// aapt resource value: 0x7f070033
			public const int linearLayout15 = 2131165235;
			
			// aapt resource value: 0x7f07001a
			public const int linearLayout2 = 2131165210;
			
			// aapt resource value: 0x7f070042
			public const int linearLayout3 = 2131165250;
			
			// aapt resource value: 0x7f07001e
			public const int linearLayout7 = 2131165214;
			
			// aapt resource value: 0x7f07001f
			public const int linearLayout9 = 2131165215;
			
			// aapt resource value: 0x7f070005
			public const int linearlayouti = 2131165189;
			
			// aapt resource value: 0x7f070003
			public const int linearlayoutiG = 2131165187;
			
			// aapt resource value: 0x7f070012
			public const int linearlayoutiH = 2131165202;
			
			// aapt resource value: 0x7f070045
			public const int menu = 2131165253;
			
			// aapt resource value: 0x7f07003d
			public const int panelView1 = 2131165245;
			
			// aapt resource value: 0x7f07003b
			public const int sButtonSave = 2131165243;
			
			// aapt resource value: 0x7f070036
			public const int sMaxP = 2131165238;
			
			// aapt resource value: 0x7f070032
			public const int sMaxR = 2131165234;
			
			// aapt resource value: 0x7f070026
			public const int sMaxX = 2131165222;
			
			// aapt resource value: 0x7f07002a
			public const int sMaxY = 2131165226;
			
			// aapt resource value: 0x7f07003a
			public const int sMaxYaw = 2131165242;
			
			// aapt resource value: 0x7f07002e
			public const int sMaxZ = 2131165230;
			
			// aapt resource value: 0x7f070035
			public const int sMinP = 2131165237;
			
			// aapt resource value: 0x7f070031
			public const int sMinR = 2131165233;
			
			// aapt resource value: 0x7f070025
			public const int sMinX = 2131165221;
			
			// aapt resource value: 0x7f070029
			public const int sMinY = 2131165225;
			
			// aapt resource value: 0x7f070039
			public const int sMinYaw = 2131165241;
			
			// aapt resource value: 0x7f07002d
			public const int sMinZ = 2131165229;
			
			// aapt resource value: 0x7f070020
			public const int sText1 = 2131165216;
			
			// aapt resource value: 0x7f070021
			public const int sText2 = 2131165217;
			
			// aapt resource value: 0x7f070022
			public const int sText3 = 2131165218;
			
			// aapt resource value: 0x7f070024
			public const int sText4 = 2131165220;
			
			// aapt resource value: 0x7f070028
			public const int sText5 = 2131165224;
			
			// aapt resource value: 0x7f07002c
			public const int sText6 = 2131165228;
			
			// aapt resource value: 0x7f070030
			public const int sText7 = 2131165232;
			
			// aapt resource value: 0x7f070034
			public const int sText8 = 2131165236;
			
			// aapt resource value: 0x7f070038
			public const int sText9 = 2131165240;
			
			// aapt resource value: 0x7f07001d
			public const int sTextD = 2131165213;
			
			// aapt resource value: 0x7f070018
			public const int sToggle1 = 2131165208;
			
			// aapt resource value: 0x7f07001b
			public const int sToggle2 = 2131165211;
			
			// aapt resource value: 0x7f070019
			public const int sToggleText1 = 2131165209;
			
			// aapt resource value: 0x7f07001c
			public const int sToggleText2 = 2131165212;
			
			// aapt resource value: 0x7f070014
			public const int sample_main_layout = 2131165204;
			
			// aapt resource value: 0x7f070006
			public const int seekBar1i = 2131165190;
			
			// aapt resource value: 0x7f070008
			public const int seekBar2i = 2131165192;
			
			// aapt resource value: 0x7f07000a
			public const int seekBar3i = 2131165194;
			
			// aapt resource value: 0x7f07000c
			public const int seekBar4i = 2131165196;
			
			// aapt resource value: 0x7f07000e
			public const int seekBar5i = 2131165198;
			
			// aapt resource value: 0x7f070010
			public const int seekBar6i = 2131165200;
			
			// aapt resource value: 0x7f070040
			public const int seekBarX = 2131165248;
			
			// aapt resource value: 0x7f070043
			public const int seekBarY = 2131165251;
			
			// aapt resource value: 0x7f070015
			public const int sliding_tabs = 2131165205;
			
			// aapt resource value: 0x7f07003c
			public const int textView0 = 2131165244;
			
			// aapt resource value: 0x7f07003e
			public const int textView1 = 2131165246;
			
			// aapt resource value: 0x7f070000
			public const int textView1a = 2131165184;
			
			// aapt resource value: 0x7f070007
			public const int textView1i = 2131165191;
			
			// aapt resource value: 0x7f07003f
			public const int textView2 = 2131165247;
			
			// aapt resource value: 0x7f070002
			public const int textView2a = 2131165186;
			
			// aapt resource value: 0x7f070009
			public const int textView2i = 2131165193;
			
			// aapt resource value: 0x7f07000b
			public const int textView3i = 2131165195;
			
			// aapt resource value: 0x7f07000d
			public const int textView4i = 2131165197;
			
			// aapt resource value: 0x7f07000f
			public const int textView5i = 2131165199;
			
			// aapt resource value: 0x7f070011
			public const int textView6i = 2131165201;
			
			// aapt resource value: 0x7f070004
			public const int textViewTitle = 2131165188;
			
			// aapt resource value: 0x7f070041
			public const int textViewX = 2131165249;
			
			// aapt resource value: 0x7f070044
			public const int textViewY = 2131165252;
			
			// aapt resource value: 0x7f070016
			public const int viewPager = 2131165206;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Accelerometer = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Inverse = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Settings = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Target = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f060000
			public const int actionbar_main = 2131099648;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int CustomActionBarTheme = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int MyActionBar = 2131034113;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
